### ISSUE TITLE
how to run KorokEngine in iOS or Android？

### ISSUE THREAD

**Issue by zhengying** [KorokEngine/alpha-demo#2]
korokEngine is good project, how to running it in iOS or Android.

**Comment by ntop001** [comment]
You can use gomobile to build apk/.app for Android/iOS. But it'll has some restrictions. Another way is to generate library and use it int Android or Xcode Project, you can see I what I did here: [port a Golang game to Android](https://dev.to/ntoooop/just-port-a-golang-game-to-android--3a9f)  [Port a Golang game to iOS](https://dev.to/ntoooop/port-a-golang-game-to-ios-p2c)
