### ISSUE TITLE
demo中gui运行报错

### ISSUE THREAD

**Issue by LanceAdd** [KorokEngine/alpha-demo#4]
# go run main.go
# korok.io/korok/gui/auto
../../korok.io/korok/gui/auto/gui_lib.go:84:21: not enough arguments in call to lm.Context.ColorBackground
        have (gui.EventType, *gui.Rect, float32)
        want (gui.EventType, *gui.Rect, gfx.Color, gfx.Color, float32)
貌似又是老哥你调整了什么

**Comment by ntop001** [comment]
@shanyujie 嗯，korok/gui/auto 中的代码有点过期了，需要和gui/包下的代码同步一下。

**Comment by ntop001** [comment]
已修复
